version: '3'
services:
  server:
    container_name: server
    build:
      context: ./sktServer
      args:
        DOMAIN: 13.125.3.108
    ports:
      - "8080:8080"
  client:
    container_name: client
    build: ./sktclient
    ports:
      - "8000:8000"
    depends_on:
      - server
  nginx:
    container_name: nginx
    # image: proxy
    build: ./.nginx
    depends_on:
      - server
      - client
#    volumes:
#      - .nginx/conf.d:/etc/nginx/conf.d
#      - .nginx/zerossl:/var/www/zerossl/.well-known/pki-validation
#      - .nginx/cert:/cert
    ports:
      - 80:80
#      - 443:443