server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://52.79.220.127:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: 123
    hikari:
      maximum-pool-size: 12
  redis:
    host: 52.79.220.127
    port: 6379
    password: 123

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 31MB

mybatis:
  config-location: classpath:/config/mybatis-config.xml


# instagram api
# id: 2119769111527249
# key: d16e598d45c983d5b38b53fa4a05e4fb